package compiler.lexer;

public enum TokenType {
    // Literals
    STRING, NUMBER, BOOLEAN, IDENTIFIER, COLOR, UNIT,

    // Keywords
    PAGE, WINDOW, COLUMN, ROW, TEXT, BUTTON, HEADING, PARAGRAPH,
    ROUTE, COMPONENT, DATABASE, ANIMATE, FETCH, PRINT,
    IF, ELSE, WHILE, FOR, IN, RETURN, IMPORT, FROM, AS,
    CLASS, INTERFACE, ENUM, EXTENDS, IMPLEMENTS, NEW,
    ASYNC, AWAIT, FUNCTION, VAR, CONST, LET, THIS, SUPER,
    NULL, TRUE, FALSE, SELF,
    ON, CLICK, ENTER, SUBMIT, CHANGE, HOVER, FOCUS, BLUR,
    ROUTER, BROWSER, WINDOW_PROP, APP,

    // Operators
    ASSIGN, EQUAL, NOT_EQUAL, LESS, GREATER, LESS_EQUAL, GREATER_EQUAL,
    PLUS, MINUS, MULTIPLY, DIVIDE, MODULO,
    AND, OR, NOT,
    PLUS_ASSIGN, MINUS_ASSIGN, MULTIPLY_ASSIGN, DIVIDE_ASSIGN,
    ARROW, DOT, COLON, DOUBLE_COLON, QUESTION,

    // Delimiters
    LPAREN, RPAREN, LBRACE, RBRACE, LBRACKET, RBRACKET,
    SEMICOLON, COMMA, NEWLINE, EOF,

    // Special
    INDENT, DEDENT, WHITESPACE, COMMENT
}
